[general]
import = [
  "C:\\Users\\ASUS\\AppData\\Roaming\\alacritty\\theme\\themes\\argonaut.toml",
  "C:\\Users\\ASUS\\AppData\\Roaming\\alacritty\\keybinding.toml",
]
working_directory = "E:\\$Terminal-Home\\"
live_config_reload = true

[terminal]
shell = { program = "pwsh", args = ["-NoLogo"] }

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
dimensions = { columns = 110, lines = 28 }
position = { x = 300, y = 100 }
padding = { x = 5, y = 5 }
opacity = 0.8
title = "08ED"
dynamic_title = true

[cursor]
style = { shape = "Beam", blinking = "On" }
